version: '3.6'

services:
  db:
    image: postgres
    volumes:
      - gsn-data:/var/lib/postgresql/data/
    networks:
      - edgeproxy_proxy-mesh
  gsn_web:
    build:
      context: .
      dockerfile: Dockerfile-django
    volumes:
      - .:/code
      ## Uncomment the following during production.
      ##- /etc/letsencrypt/:/etc/letsencrypt/
      ##- /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    networks:
      edgeproxy_proxy-mesh:
        aliases:
          - gsn_web
    expose:
      - "80"
    # Uncomment the following during development:
    ports:
      - "80:80"
    environment:
      - SECRET_KEY=developerkey
    depends_on:
      - db

volumes:
  gsn-data:
networks:
  edgeproxy_proxy-mesh:
  # Uncomment the following during production.
  #  external: true
